### ISSUE TITLE
Add Standard Deviation to signal output

### ISSUE THREAD

**Issue by shadetree01010100** [nio-blocks/reduce#16]
Can it be added to the outputs? I have a test service using control bands where I could actually be using Reduce/Stream, the only reason I am not is that I don't want to do S.D. calculations with blocks, seems complicated. This would require far fewer resources than the control band.

**Comment by mattdodge** [comment]
The problem with standard deviation is it requires keeping track of the full data set. The ReduceStream block is optimized to only keep track of summary data about the information coming through.

The ControlBands block doesn't actually do standard deviation, it's a moving range calculation that doesn't require keeping track of the raw data. We could potentially add that calculation to the reduce block but I might actually argue that the blocks are one in the same at that point.
